name: flutter_ui_challenge
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  intl: 0.16.1
  jiffy_vi: ^3.0.1+1
  fluttertoast: ^7.0.2
  horizontal_data_table: ^1.0.5+5
  pull_to_refresh: ^1.6.0

  base_app: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
